### PR TITLE
CHANGE Committee square sizes now adjusts when the window is being re…

### PR DESCRIPTION
**Pull request by patagbayani**
…sized

### CODE REVIEW

**Review by LimyuA — CHANGES_REQUESTED** [review]
napuputol padin yung words sa loob. I think mas okay kung lumiliit lang yung square along with the words pero same aspect ratio, paconsult nalang sa front end lead (@nchlnnmrvnz) para sa dapat na itsura pag maliit screen
image

**Review by jjxiv — CHANGES_REQUESTED** [review]
Hello @patagbayani siguro yung resizing nalang pa-check ulit ditoo, okay na siya overall pero resizing nalang for mobile devices kulang then goods na to most likely, ty.

meetTheCommittees00

**Review by LimyuA — APPROVED** [review]
All good

**Comment by jjxiv** [comment]
Yo @patagbayani its now working but, needs to be centered more on smaller sized screen like pixel 5 (dimension na ginamit ko sa inspect)

**The content needs to be centered.**
meetTheCommittees01

**Review by jjxiv — APPROVED** [review]

**Pull request merged**
