### PR TITLE
feat: FIX responsiveness of text when on smaller screens

### PR DESCRIPTION
**Pull request by Dale0122**
- ADDED custom screen size on tailwind.config.js to fix responsiveness on smaller screens
- EDITED Committee font size when on smaller screen to resolve text going off the screen

Screenshot 2023-11-10 235239

### CODE REVIEW

**Review by LimyuA — CHANGES_REQUESTED** [review]
Still not responsive on mobile devices and smaller web browsers. for the smaller web browser, add left and right margins para hindi sagad yung text sa gilid

image

image

**Comment by Dale0122** [comment]
Mali ata pag view mo sa developer tools kasi sakin okay sya double-checked

**Comment by Dale0122** [comment]
Problem was on Header and Footer. Not mine.

**Comment by LimyuA** [comment]
ganyan sa pag hindi zinoom out. zinzoom out mo so ibig sabihin di sya responsive kase kailangan mo pa izoom out

image

**Comment by LimyuA** [comment]
> Problem was on Header and Footer. Not mine.
nakasagad padin sa gilid kahit tanggalin header at footer

image

**Comment by Dale0122** [comment]
What do you mean nakasagad sa gilid?

**Review by LimyuA — APPROVED** [review]
All good

**Review by LimyuA — CHANGES_REQUESTED** [review]
make header text responsive

**Comment by Dale0122** [comment]
Most responsive I can get. Wala ako nakita sa buong website na hinihingi mong specification. Halos lahat ng ibang header di nababago font size depending sa screen size.

**Review by LimyuA — APPROVED** [review]

**Pull request merged**
