### PR TITLE
feat: ADD Projects Overview with moving scroll carousel

### PR DESCRIPTION
**Pull request by ralphcajipe**
### MODIFIED
Must install **daisyUI** (a Tailwind CSS plugin) in order for these modified files to work in harmony
- /app/projects/**page.tsx** -> Now properly calls ThesisPoster constant from ThesisPosterCard.tsx component
- /app/**globals.css** ->  Added CSS to ThesisPosterCard component
- /app/**layout.tsx** -> Added better comments, added Scroll Carousel CDN link to work for all instead of npm install, and I used `async` property in JS scripts of CDN links in order to [prevent synchronous scripts](https://nextjs.org/docs/messages/no-sync-scripts) which can impact poorly our webpage performance.
- /components/**ThesisPosterCard.tsx** -> Refactored to be able to combine Scroll Carousel and daisyUI's stack images component

1. Install daisyUI:
    `npm i -D daisyui@latest`

2. Then add daisyUI to your `tailwind.config.ts` file:
```
plugins: [require("daisyui")],
  daisyui: {
    themes: ["light"],
  },
```
image

### NEW
I had to experiment with the look and feel in terms of efficiency of our 20 thesis posters (the majority in PNG) so I had to create new image directories of the thesis posters in `/public` directory of the codebase.
image

I found that we need to improve website performance—the **WebP** format is lighter than PNG and JPEG, so a page with WebP images will load faster for users in **production**. It also saves internet bandwidth—WebP frees up bandwidth and could allow us to offer a richer experience. For that, do we need to convert our images to a WebP format? See this [guide ](https://www.freecodecamp.org/news/make-your-website-load-lightning-fast-with-webp-images-cf55c98ac0a2/#:~:text=Fortunately%2C%20there%20is%20still%20some,more%20than%20twice%20as%20fast.) from freecodecamp.

### Screen record of my npm run dev https://www.loom.com/share/a84e51ccc37f4e11bd33d9938e556966?sid=ea473667-1edf-4634-bfd6-b21dc829f262

### CODE REVIEW

**Review by jjxiv — CHANGES_REQUESTED** [review]
The scroll functionality is good and works for now but i have some concerns:
- I'll be consulting the automatic scroll animation with the Front-lead dev
- The horizontal scroll should include manual dragging
- There are thin borders around the posters should be removed
- Add the other layers of posters based on thesis category (refer to figma design)


I will be requesting changes for these since it's not yet needed to be published temporarily. Thank you.

**Comment by ralphcajipe** [comment]
> The scroll functionality is good and works for now but i have some concerns:
> 
> * I'll be consulting the automatic scroll animation with the Front-lead dev
> * The horizontal scroll should include manual dragging
> * There are thin borders around the posters should be removed
> * Add the other layers of posters based on thesis category (refer to figma design)
> 
> I will be requesting changes for these since it's not yet needed to be published temporarily. Thank you.

UPDATE: Right, thin borders are now removed with a new commit to this PR 👍 manual dragging might be easy and layers of posters are a bit tricky so I will need to put @kylekce on this loop for help.

**Review by nchlnnmrvnz — CHANGES_REQUESTED** [review]
Do the following changes for the ThesisPosterCard.tsx. In this file, create (if you haven't already):
- ThesisPoster (it will serve as the poster's container)
- ThesisStack (contains several calls to the ThesisPoster for stacking the posters)
- ThesisCarousel (contains and displays the ThesisStack)

We will push through with the use of icons for the mean time (so no shuffling needed for now), but they should remain stacked like the original design. Use either react or bootstrap icons related to each category.

**Comment by ralphcajipe** [comment]
@kylekce and I are still brainstorming

**Comment by ralphcajipe** [comment]
@jjxiv @nchlnnmrvnz 
Kyle will do a new commit here tomorrow. There is a working front end for this.

**Comment by ralphcajipe** [comment]
hello @jjxiv @nchlnnmrvnz @yanaagi @LimyuA , Kyle did a new [commit ](https://github.com/yanaagi/cs-expo-2023/pull/104/commits/e1d647f8b3e481e96b9b9ff9e92e079bf33c469a) just now. Thank you.

**Comment by jjxiv** [comment]
@ralphcajipe Hello gm, so far these are close with the specifications, and I have other requests for these changes:

- The icons should be resized a bit smaller, in order to blend with the minimalist style of the website, I have no specific requirement for the size (but should blend with the minimalist style)
- The automatic scroll should be very slow (try to experiment with this), a manual scroll should be also added to give the user more control of the UI and check the projects
- The border of the whole carousel should be widened, in order to really let the carousel exceed the browser page, giving it a feel of letting the project cards coming from outside the browser

**Comment by ralphcajipe** [comment]
Fixes:
- icons resized to look a bit smaller
- automatic scroll cycles in 4 seconds to give a very slow impression, with manual dragging support
- left and right arrow buttons with fading effect on mouse hover
- carousel exceeds browser page, an impression the carousel is coming from outside the browser
- /app/**layout.tsx** -> Added Glide's Theme Stylesheet for manual dragging and arrow buttons to work
- /app/projects/**page.tsx** -> Calls the new `ProjectsCarousel` component
- /components/**ProjectsCarousel.tsx** -> the new component that runs on Glide.js

**Review by jjxiv — APPROVED** [review]

**Review by nchlnnmrvnz — APPROVED** [review]

**Pull request merged**
