### PR TITLE
ADD typewriter animation and router for cs expo and dev day

### PR DESCRIPTION
**Pull request by djhbas**
image

image

image

-ADD the home directory with 3 files
-UPDATE the global.css to ADD custom typewriter animation (can't convert to tailwind)

### CODE REVIEW

**Review by LimyuA — CHANGES_REQUESTED** [review]
check discord for changes

**Review by nchlnnmrvnz — CHANGES_REQUESTED** [review]
- no additional files are allowed in your folder for home (remove index.tsx and router.tsx)
- combine the contents in the page.tsx
- create components for your design (you imported the function, not the component)

**Review by LimyuA — CHANGES_REQUESTED** [review]
Delete index.tsx

**Review by ralphcajipe — COMMENTED** [review]
Deleted duplicates from DJ in this PR

**Pull request closed without merging**
