### PR TITLE
Homepagev2

### PR DESCRIPTION
**Pull request by djhbas**
Responsive: in progress

### CODE REVIEW

**Review by nchlnnmrvnz — CHANGES_REQUESTED** [review]
- border around the button is missing (check Figma closely) medyo subtle 'yung design baka naoverlook mo lang

**Review by jjxiv — APPROVED** [review]
So far yung nakita kong conflict is edited lang na front-end text font and minimal stuff

**Comment by jjxiv** [comment]
Hello @djhbas, aside from the text animation, cs expo, and dev day from the home page, I'll be needing the prototype for the partners **ASAP**:

home_page_00

I'll be waiting till the end of the day, if not pls give updates ty

**Review by nchlnnmrvnz — CHANGES_REQUESTED** [review]
A few more additional changes (esp. for responsiveness):

1. Centered typewriting animation. It's left aligned on desktop. Please ensure that they are the same. Also, please add the sponsors' circles so we can check already.
bas-1114-1

2. Text too small. It is no longer readable. You may refer to the CS Expo and/or Dev Day pages to examine how their text resizes. Also, there is a semicolon above that must be removed. I think you mistakenly pressed that when coding.
bas-1114-2

3. Content is not centered vertically. It's too low compared to the first and second ones.
bas-1114-3


Additional notes/reminders: Please don't forget that it is advisable to avoid any kind of hardcoded values. It may look okay on your monitor but phones have a smaller viewport for both width and height so it is essential to avoid targeting breakpoints (e.g. sm, md, lg).

**Review by jjxiv — APPROVED** [review]
Needs responsiveness for partners, but for now i'll approve it. ty. @djhbas

**Review by LimyuA — APPROVED** [review]

**Review by nchlnnmrvnz — APPROVED** [review]

**Pull request merged**
