### PR TITLE
fix: arrow buttons now outside of carousel

### PR DESCRIPTION
**Pull request by ralphcajipe**
image

image

### CODE REVIEW

**Comment by ralphcajipe** [comment]
hello @LimyuA, there is now responsiveness for common/modern mobile phones. the dimensions i tested are from chrome, edge, and firefox-dev browsers.

**Comment by ralphcajipe** [comment]
hello @LimyuA, here is the SVG images as slides and their responsiveness
 
image
image

**Comment by ralphcajipe** [comment]
for the 6th commit:
image

**Comment by jjxiv** [comment]
Hello @ralphcajipe, your changes works as expected but I need one more request. The pictures shown below:

- It should work on the smallest device width
projects_overview_03

Then aside from this request, responsiveness would be complete. Thanks.

**Comment by ralphcajipe** [comment]
hello @LimyuA, the svg images should look okay now with its back layer. thank you.

hello @jjxiv, thank you for your feedback. this time i tried my best to show the slide on 320px and it still looks decent, but there is a slight tradeoff. the carousel arrows won't fit as normal. i also did some research on a UX Design agency's [research in 2022](https://worship.agency/mobile-screen-sizes-for-2022-based-on-data-from-2021) and found that 320px wide devices are now only being used by around 3% of mobile users. i can recall using 320px devices back in 2008-2010, when I was just 9 years old. while these devices were famous back then, their usage has significantly declined over time. i hope this info can help the dev team.

image
image
image

**Comment by rnlguday** [comment]
trueeee

**Comment by jjxiv** [comment]
@nchlnnmrvnz  @LimyuA  what do you think? 


@ralphcajipe  I'm concerned on phones that have fold that may fit into 320px brother

As you can see here, it is almost the same to 320 px but it can be resized. 
However in situations like this if the person wants to multi-task then, what would be the plan for UI?
projects_overview_04
_Source:[_Multitask Samsung Galaxy Fold](https://www.youtube.com/watch?v=KRTjXV1TdJM&ab_channel=TechAdvisor)_

On another note, here are the samples for screens with close to 320px:
projects_overview_05
_Source:[Dimensions of Samsung Galaxy Fold](https://www.dimensions.com/element/samsung-galaxy-fold-2019)_

**Comment by ralphcajipe** [comment]
**320px**
image

**galaxy fold**
image

**Review by jjxiv — APPROVED** [review]

**Review by LimyuA — CHANGES_REQUESTED** [review]
May point na nawawala yung arrow minsan andon arrow pero wala yung white na border, wala din sa gitna ng screen yung buong carousel, and lastly padagdag lang ng space yung sa ibabaw ng arrows and ilalim ng carousel masyado masikip for me
image

image

**Comment by ralphcajipe** [comment]
nov 16 2023

**320px**
image

**galaxy fold**
image

**pixel 7**
image

**desktop/laptop**
image

**Review by LimyuA — APPROVED** [review]

**Pull request merged**
