### PR TITLE
Add responsiveness

### PR DESCRIPTION
**Pull request by kylekce**

### CODE REVIEW

**Review by LimyuA — CHANGES_REQUESTED** [review]
In the responsiveness for a smaller browser, the arrows overlap with the picture. 
image

In the responsiveness for mobile devices some elements still overlap with each other

image

**Comment by kylekce** [comment]
@LimyuA Can you check now
image

**Review by LimyuA — APPROVED** [review]
All good

**Review by LimyuA — APPROVED** [review]
All good

**Pull request merged**
